<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gdpr_record"
 *
 * Auto generated by Extension Builder 2018-06-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'GDPR Record of Processing',
    'description' => 'Generate a record of processing (Verarbeitungsverzeichnis) according to gdpr based on the existing tables or by specifying the parameters manually.',
    'category' => 'module',
    'author' => 'Christoph Balogh',
    'author_email' => 'cb@lustige-informatik.at',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
